repos=(
  aleo-fonts
  android_translation_layer
  android_translation_layer-git
  archosaur
  archosaur-git
  art_standalone
  art_standalone-git
  bionic_translation
  bionic_translation-git
  blockbench
  blockbench-bin
  blockbench-git
  bsd-compat-headers
  bugwarrior
  comictagger-beta
  curseforge
  curseforge-appimage
  dissent
  dissent-bin
  dissent-git
  dpitunnel
  dpitunnel-bin
  dpitunnel-git
  espanso-git
  extracker-git
  eza-git
  fast-discord-git
  flaresolverr
  flaresolverr-bin
  funchook
  gpt-engineer
  halloy
  halloy-bin
  halloy-git
  illarion-bin
  imgbrd-grabber-appimage
  imv-git
  java-openjdk-wakefield
  jsoncons
  jwt-cpp
  libfm-qt-git
  libopensles-standalone
  libopensles-standalone-git
  librespot
  linux-command-gpt
  linux-command-gpt-git
  lxqt-menu-data-git
  lxqt_wallet
  lxqt_wallet-git
  nuitka
  openkeeper-git
  opennox
  opennox-bin
  opennox-git
  openssh-askpass
  openssl-static
  opentracker
  otf-monocraft
  otf-sans-forgetica
  otf-unifont
  packwiz-git
  pcmanfm-qt-git
  porla
  prismlauncher-git
  prismlauncher-qt5
  prismlauncher-qt5-bin
  progress-quest-bin
  python-baycomp
  python-cfscrape
  python-comicfn2dict
  python-confusables
  python-isocodes
  python-magika
  python-niquests
  python-pox
  python-pyrate-limiter-2
  python-selenium
  python-settngs
  python-syncedlyrics
  python-urllib3-future
  python-user_agent2
  python-wassima
  python-xvfbwrapper
  python-zipremove
  qbittorrent-nightwalker
  radeon-gpu-profiler
  ripcord
  ripcord-arch-libs
  ripme
  ripme-bin
  ripme-git
  scientifica-font
  skia-sharp-atl
  skia-sharp-atl-git
  soundsense
  soundsense-rs-git
  spoofdpi
  spoofdpi-bin
  spoofdpi-git
  stevenarella-git
  superseedr
  thesage
  tile38
  tile38-bin
  trelby
  trelby-git
  trillian
  ttc-monocraft
  ttf-game-fonts
  ttf-miracode
  ttf-signika
  ttf-unifont
  usockets
  uwebsockets
  vimv-git
  wolfssl-jni
  yt-spammer-purge
  zaread-git
)

for repo in "${repos[@]}"; do
  echo ''
  echo "--> Pulling ${repo}"
  archosaur --pull "${repo}"
done
