[python-langchain-core]
# source = "pypi"
# pypi = "langchain"
source = "github"
github = "langchain-ai/langchain"
prefix = "langchain-core=="
include_regex = 'langchain-core==\d+\.\d+\.\d+'
use_max_tag = true
