name: Build

on:
  workflow_call:
    inputs:
      packages:
        description: List of packages to build
        type: string
        default: '[]'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/archlinux/archlinux:base-devel
    if: ${{ inputs.packages != '[]' && inputs.packages != '[""]' && inputs.packages != '' }}
    strategy:
      matrix:
        package: ${{ fromJson(inputs.packages) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Update system and install dependencies
        run: |
          echo -e "\n[multilib]\nInclude = /etc/pacman.d/mirrorlist\n" >> /etc/pacman.conf
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed git fd jq namcap eza ripgrep

      - name: Create user to run makepkg
        run: |
          useradd -m dev
          echo "dev ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/01_dev

      - name: chown for dev
        run: |
          chown -R dev: .

      - name: Handle PGP keys
        run: |
          cd ${{ matrix.package }}
          source PKGBUILD
          for key in ${validpgpkeys}
          do
            runuser -u dev -- gpg --recv-keys ${key}
          done

      - name: Install yay
        run: |
          runuser -u dev -- git clone https://aur.archlinux.org/yay.git
          cd yay
          runuser -u dev -- makepkg -csri --noconfirm

      - name: Install package dependencies from AUR
        shell: bash --noprofile --norc {0}
        run: |
          cd ${{ matrix.package }}
          source PKGBUILD
          echo ${depends[@]} ${makedepends[@]} ${checkdepends[@]}
          packages_all=()
          packages_all+=("${depends[@]}")
          packages_all+=("${makedepends[@]}")
          packages_all+=("${checkdepends[@]}")
          packages_for_pacman=()
          packages_for_yay=()
          temp=$(pacman -S --noconfirm --asdeps ${depends[@]} ${makedepends[@]} ${checkdepends[@]} 2>&1 | rg "error: target not found: " -r "")
          IFS=$'\n' read -r -d '' -a packages_for_yay <<< "${temp}"
          echo "packages_for_pacman: ${packages_for_pacman[@]}"
          echo "packages_for_yay: ${packages_for_yay[@]}"
          echo "packages_all: ${packages_all[@]}"
          for pkg in "${packages_all[@]}"
          do
            echo "pkg: ${pkg}"
            found=0
            for pkgyay in "${packages_for_yay[@]}"
            do
              echo "pkgyay: ${pkgyay}"
              if [[ "${pkg}" == "${pkgyay}" ]]
              then
                found=$(( found+1 ))
              fi
            done
            if [[ ${found} -eq 0 ]]
            then
              packages_for_pacman+=("${pkg}")
            fi
          done
          echo "pacman will install these packages: ${packages_for_pacman[@]}"
          pacman -S --noconfirm --asdeps "${packages_for_pacman[@]}"
          echo "yay will install these packages: ${packages_for_yay[@]}"
          runuser -u dev -- yay -S --noconfirm --asdeps "${packages_for_yay[@]}"

      - name: Build and install package
        run: |
          cd ${{ matrix.package }}
          source PKGBUILD
          # Remove eza to install eza-git
          if [[ "${pkgname}" == "eza-git" ]]
          then
            echo "Removing preinstalled eza"
            pacman -R --noconfirm eza
          fi
          # Remove jdk-openjdk to install. It conflicts.
          if [[ "${pkgbase}" == "java-openjdk-wakefield" ]]
          then
            runuser -u dev -- makepkg -csr --noconfirm
            pacman -R --noconfirm jdk21-openjdk
            runuser -u dev -- yay -U --noconfirm jre-openjdk-wakefield-headless-*.pkg.tar.zst
            pacman -R --noconfirm jre-openjdk-wakefield-headless
            runuser -u dev -- yay -U --noconfirm jre-openjdk-wakefield-2*.pkg.tar.zst
            pacman -R --noconfirm jre-openjdk-wakefield
            runuser -u dev -- yay -U --noconfirm jdk-openjdk-wakefield-*.pkg.tar.zst
            runuser -u dev -- yay -U --noconfirm openjdk-wakefield-doc-*.pkg.tar.zst
            runuser -u dev -- yay -U --noconfirm openjdk-wakefield-src-*.pkg.tar.zst
          elif [[ "${pkgbase}" == "espanso-git" ]]
          then
            runuser -u dev -- makepkg -csr --noconfirm
            runuser -u dev -- yay -U --noconfirm espanso-x11-git-*.pkg.tar.zst
            pacman -R --noconfirm espanso-x11-git
            runuser -u dev -- yay -U --noconfirm espanso-wayland-git-*.pkg.tar.zst
          else
            runuser -u dev -- makepkg -csri --noconfirm
          fi

      - name: Grab built package's filename
        run: |
          cd ${{ matrix.package }}
          source PKGBUILD
          counter=0
          for single_package in ${pkgname[@]}
          do
            counter=$((counter+1))
            echo "filename_${counter}=$(eza ${single_package}*.pkg.tar.zst -I *-debug-*.pkg.tar.zst)" >> $GITHUB_ENV
          done
          echo "Found ${counter} artifacts"
          if eza *-debug-*.pkg.tar.zst
          then
            echo "filename_debug=$(eza *-debug-*.pkg.tar.zst)" >> $GITHUB_ENV
          fi

      - name: Upload artifact
        if: env.filename_1
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.filename_1 }}
          path: |
            ${{ matrix.package }}/${{ env.filename_1 }}

      - name: 'Upload artifact #2'
        if: env.filename_2
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.filename_2 }}
          path: |
            ${{ matrix.package }}/${{ env.filename_2 }}

      - name: 'Upload artifact #3'
        if: env.filename_3
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.filename_3 }}
          path: |
            ${{ matrix.package }}/${{ env.filename_3 }}

      - name: 'Upload artifact #4'
        if: env.filename_4
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.filename_4 }}
          path: |
            ${{ matrix.package }}/${{ env.filename_4 }}

      - name: 'Upload artifact #5'
        if: env.filename_5
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.filename_5 }}
          path: |
            ${{ matrix.package }}/${{ env.filename_5 }}

      - name: Upload debug artifacts
        if: env.filename_debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.filename_debug }}
          path: |
            ${{ matrix.package }}/${{ env.filename_debug }}
