name: Build

on:
  workflow_call:
    inputs:
      packages:
        description: List of packages to build
        type: string
        default: '[]'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    if: ${{ inputs.packages != '[]' && inputs.packages != '[""]' && inputs.packages != '' }}
    strategy:
      matrix:
        package: ${{ fromJson(inputs.packages) }}
      fail-fast: false

    steps:
      - name: Test
        run: |
          echo ${{ matrix.package }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Update system and install dependencies
        run: |
          sed -i 's/#\[multilib\]/\[multilib\]/' /etc/pacman.conf
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed git fd jq namcap eza ripgrep

      - name: Create user to run makepkg
        run: |
          useradd -m dev
          echo "dev ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/01_dev

      - name: chown for dev
        run: |
          chown -R dev: .

      - name: Handle PGP keys
        run: |
          cd ${{ matrix.package }}
          source PKGBUILD
          for key in ${validpgpkeys}
          do
            runuser -u dev -- gpg --recv-keys ${key}
          done

      - name: Install yay
        run: |
          runuser -u dev -- git clone https://aur.archlinux.org/yay.git
          cd yay
          runuser -u dev -- makepkg -csri --noconfirm

      - name: Install package dependencies from AUR
        shell: bash --noprofile --norc {0}
        run: |
          cd ${{ matrix.package }}
          source PKGBUILD
          echo ${depends[@]} ${makedepends[@]} ${checkdepends[@]}
          packages_for_yay=()
          packages_for_yay=$(pacman -S --noconfirm --asdeps ${depends[@]} ${makedepends[@]} ${checkdepends[@]} 2>&1 | rg "error: target not found: " -r "")
          if [[ -n "${packages_for_yay}" ]]
          then
            mapfile -t packages < \
              <(comm -23 \
                <(IFS=$'\n'; echo "${depends[*]} ${makedepends[*]} ${checkdepends[*]}" | sort) \
                <(IFS=$'\n'; echo "${packages_for_yay[*]}" | sort) \
              )
            echo "pacman will install these: ${packages[@]}"
            pacman -S --noconfirm --asdeps "${packages[@]}"
            echo "yay will install these: ${packages_for_yay[@]}"
            runuser -u dev -- yay -S --noconfirm --asdeps "${packages_for_yay[@]}"
          else
            echo "pacman installed all packages successfully!"
          fi

      - name: Build and install package
        run: |
          cd ${{ matrix.package }}
          runuser -u dev -- makepkg -csri --noconfirm

      - name: Grab built package's filename
        run: |
          cd ${{ matrix.package }}
          source PKGBUILD
          counter=0
          for single_package in ${pkgname}
          do
            counter=$((counter+1))
            echo "filename_${counter}=$(eza ${single_package}*.pkg.tar.zst -I *-debug-*.pkg.tar.zst)" >> $GITHUB_ENV
          done
          echo "Found ${counter} artifacts"
          if eza *-debug-*.pkg.tar.zst
          then
            echo "filename_debug=$(eza *-debug-*.pkg.tar.zst)" >> $GITHUB_ENV
          fi

      - name: Upload artifact
        if: env.filename_1
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.filename_1 }}
          path: |
            ${{ matrix.package }}/${{ env.filename_1 }}

      - name: 'Upload artifact #2'
        if: env.filename_2
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.filename_2 }}
          path: |
            ${{ matrix.package }}/${{ env.filename_2 }}

      - name: Upload debug artifacts
        if: env.filename_debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.filename_debug }}
          path: |
            ${{ matrix.package }}/${{ env.filename_debug }}
